/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rent_system;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author USER
 */
public class AddCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPanel
     */
    Connection con;
    DB db;
    String ImagePath;

    public AddCarPanel(Connection con, DB db) {
        initComponents();
        this.con = con;
        this.db = db;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        CarBrandChooser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CarTypeChooser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameFiled = new javax.swing.JTextField();
        RegisterIDFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ColorChooser = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        YearChoosr = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        GearBoxChooser = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        HandiCapCheckBox = new javax.swing.JCheckBox();
        NumberSeatsSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        PPDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UploadImageButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BranchChooser = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        GazTypeChooser = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Year Model");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 153));

        CarBrandChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KIA", "DODGE", "GMC", "BMW", "TESLA", "HONDA", "HYUNDAI", "TOYOTA", " " }));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Car Brand");

        CarTypeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEDAN", "SPORT", "SUV", "LUXURY", "VAN" }));
        CarTypeChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarTypeChooserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Car Type");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Car Name");

        NameFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFiledActionPerformed(evt);
            }
        });

        RegisterIDFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterIDFiledActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Regestiration ID");

        ColorChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "GREEN", "BLUE", "YELLOW", "LIME GREEN", "BLACK ", "WHITE", "GRAY", "CYAN", "PURPLE", "TURQOISE", "ORANGE", "BROWN", "SKY BLUE", "BEIGE" }));
        ColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorChooserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Car Color");

        YearChoosr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));
        YearChoosr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearChoosrActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Year Model");

        GearBoxChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUTOMATIC", "MANUAL" }));
        GearBoxChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GearBoxChooserActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("GearBox");

        HandiCapCheckBox.setBackground(new java.awt.Color(153, 153, 153));
        HandiCapCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        HandiCapCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        HandiCapCheckBox.setText("HandiCap");
        HandiCapCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandiCapCheckBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Number of Seats");

        PPDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPDFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Price Per Day");

        UploadImageButton.setText("Upload Image");
        UploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ADD CAR");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BranchChooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Al-Basateen", "Al-Jamiaa", "Al-Safa", "Al-Azizyah", "Jeddah Airport" }));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText(" Branch");

        GazTypeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "95", "91" }));
        GazTypeChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GazTypeChooserActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Gaz Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CarBrandChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(NameFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(GazTypeChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(CarTypeChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(RegisterIDFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UploadImageButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HandiCapCheckBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(ColorChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumberSeatsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(YearChoosr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PPDField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(GearBoxChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BranchChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(150, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GearBoxChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YearChoosr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CarBrandChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarTypeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterIDFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BranchChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadImageButton)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HandiCapCheckBox)
                    .addComponent(GazTypeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NameFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFiledActionPerformed

    private void RegisterIDFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterIDFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterIDFiledActionPerformed

    private void CarTypeChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarTypeChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarTypeChooserActionPerformed

    private void ColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorChooserActionPerformed

    private void YearChoosrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearChoosrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearChoosrActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void GearBoxChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GearBoxChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GearBoxChooserActionPerformed

    private void HandiCapCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandiCapCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HandiCapCheckBoxActionPerformed

    private void PPDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPDFieldActionPerformed

    private void UploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageButtonActionPerformed
//        FileFilterImage fileFilterImageJPG = new FileFilterImage("jpg", " ");
//        FileFilterImage fileFilterImagePNG = new FileFilterImage("png", " ");
//        FileFilterImage fileFilterImageSVG = new FileFilterImage("svg", " ");

        JFileChooser f = new JFileChooser("C:\\Users\\USER\\Desktop");
//        f.addChoosableFileFilter(fileFilterImageSVG);
//        f.addChoosableFileFilter(fileFilterImageJPG);
//        f.addChoosableFileFilter(fileFilterImagePNG);
        f.showOpenDialog(this);
        File image = f.getSelectedFile();

        ImagePath = image.getAbsolutePath();
        System.out.println(ImagePath);


    }//GEN-LAST:event_UploadImageButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        boolean status = true;
        String carBrand = CarBrandChooser.getItemAt(CarBrandChooser.getSelectedIndex()).toString();
        String carType = CarTypeChooser.getItemAt(CarTypeChooser.getSelectedIndex()).toString();
        String carColor = ColorChooser.getItemAt(ColorChooser.getSelectedIndex()).toString();
        String carYear = YearChoosr.getItemAt(YearChoosr.getSelectedIndex()).toString();
        String carGearBox = GearBoxChooser.getItemAt(GearBoxChooser.getSelectedIndex()).toString();
        String GazType = GazTypeChooser.getItemAt(GazTypeChooser.getSelectedIndex()).toString();
        String carName = NameFiled.getText();

        Date date = new java.util.Date("1/1/" + carYear);

        int regID = 0;
        try {
            regID = Integer.parseInt(RegisterIDFiled.getText());
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Invalid registeration ID", "Error", JOptionPane.ERROR_MESSAGE);
            status = false;
        }

        int numOfseats = Integer.parseInt(NumberSeatsSpinner.getValue().toString());
        int pricePerDay = 0;
        try {
            pricePerDay = Integer.parseInt(PPDField.getText());

        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Invalid Price per day", "Error", JOptionPane.ERROR_MESSAGE);
            status = false;
        }

        boolean handiCap = HandiCapCheckBox.isSelected();

        String branch = BranchChooser.getItemAt(BranchChooser.getSelectedIndex()).toString();
        //String Car_brand, String Regesteration_Id, String Car_type, String Car_Name, String Gas_Type, String Color, String GearBox, Date model_Year, int Number_Seats, int Price_Per_Day,  image,  boolean HandiCap_Support
        String[] street = {"Al-Basateen", "Al-Jamiaa", "Al-Safa", "Al-Azizyah", "Jeddah Airport"};
        int id = 0;
        switch (branch) {
            case "Al-Basateen":
                id = 1000;
                break;
            case "Al-Jamiaa":
                id = 1001;
                break;
            case "Al-Safa":
                id = 1002;
                break;
            case "Al-Azizyah":
                id = 1003;
                break;
            case "Jeddah Airport":
                id = 1004;
                break;
        }

        Car car = new Car(carBrand, regID + "", carType, carName, GazType, carColor, carGearBox, date, numOfseats, pricePerDay, ImagePath, handiCap,id);
        if (status){
            if (db.addCar(car)){
                JOptionPane.showMessageDialog(this, carName + " has been added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void GazTypeChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GazTypeChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GazTypeChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BranchChooser;
    private javax.swing.JComboBox<String> CarBrandChooser;
    private javax.swing.JComboBox<String> CarTypeChooser;
    private javax.swing.JComboBox<String> ColorChooser;
    private javax.swing.JComboBox<String> GazTypeChooser;
    private javax.swing.JComboBox<String> GearBoxChooser;
    private javax.swing.JCheckBox HandiCapCheckBox;
    private javax.swing.JTextField NameFiled;
    private javax.swing.JSpinner NumberSeatsSpinner;
    private javax.swing.JTextField PPDField;
    private javax.swing.JTextField RegisterIDFiled;
    private javax.swing.JButton UploadImageButton;
    private javax.swing.JComboBox<String> YearChoosr;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
