/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rent_system;

import static car_rent_system.CustomerHomePage.resultSetToTableModel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class AdminHomePage extends javax.swing.JFrame {
    
    Connection con;
    DB db;
    static GridBagLayout layout = new GridBagLayout();
    GridBagConstraints c;
    
    AddCarPanel addCarPanel;
    AdminReservationsPanel adminReservationsPanel;
    
    public AdminHomePage(Connection con, DB db) {
        initComponents();
        this.db = db;
        this.con = con;
        
        addCarPanel = new AddCarPanel(con, db);
        MyContainer.setLayout(layout);
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        MyContainer.add(addCarPanel, c);
        addCarPanel.setVisible(true);
        
        adminReservationsPanel = new AdminReservationsPanel(con, db);
        MyContainer.setLayout(layout);
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        MyContainer.add(adminReservationsPanel, c);
        adminReservationsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddCarPanelButton = new javax.swing.JButton();
        ReservationPanelButton = new javax.swing.JButton();
        SignOutPanelButton = new javax.swing.JButton();
        MyContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        AddCarPanelButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AddCarPanelButton.setText("Add Car");
        AddCarPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarPanelButtonActionPerformed(evt);
            }
        });

        ReservationPanelButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ReservationPanelButton.setText("Reservations");
        ReservationPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationPanelButtonActionPerformed(evt);
            }
        });

        SignOutPanelButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SignOutPanelButton.setText("SignOut");
        SignOutPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(AddCarPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(ReservationPanelButton)
                .addGap(177, 177, 177)
                .addComponent(SignOutPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignOutPanelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddCarPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ReservationPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MyContainer.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout MyContainerLayout = new javax.swing.GroupLayout(MyContainer);
        MyContainer.setLayout(MyContainerLayout);
        MyContainerLayout.setHorizontalGroup(
            MyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MyContainerLayout.setVerticalGroup(
            MyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCarPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarPanelButtonActionPerformed
        
        addCarPanel.setVisible(true);
        adminReservationsPanel.setVisible(false);
        

    }//GEN-LAST:event_AddCarPanelButtonActionPerformed

    private void ReservationPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationPanelButtonActionPerformed
        addCarPanel.setVisible(false);
        adminReservationsPanel.setVisible(true);
        
        
        ResultSet re = db.getAllReservations();
        adminReservationsPanel.table().setModel(resultSetToTableModel(re));
    }//GEN-LAST:event_ReservationPanelButtonActionPerformed

    private void SignOutPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutPanelButtonActionPerformed
        
        this.setVisible(false);
        new UserPage(con, db).setVisible(true);

    }//GEN-LAST:event_SignOutPanelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    
    public static TableModel resultSetToTableModel(ResultSet rs) {
        try {

            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();

            // Get the column names
            for (int column = 0; column < numberOfColumns; column++) {
                columnNames.addElement(metaData.getColumnLabel(column + 1));
            }

            // Get all rows.
            Vector rows = new Vector();

            while (rs.next()) {
                Vector newRow = new Vector();

                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }

                rows.addElement(newRow);
            }

            return new DefaultTableModel(rows, columnNames);   // AFTER THAT INVOKE .SetModel on the JTable Object...
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarPanelButton;
    private javax.swing.JPanel MyContainer;
    private javax.swing.JButton ReservationPanelButton;
    private javax.swing.JButton SignOutPanelButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
