/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rent_system;

import java.sql.*;
import java.util.InputMismatchException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class customerSignUp extends javax.swing.JFrame {

    /**
     * Creates new form customerSignUp
     */
    DB db;
    Connection con;
    
    public customerSignUp() {
        initComponents();
    }
    
    public customerSignUp(DB db) {
        initComponents();
        this.db = db;
        con = db.getCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        Phone_Field = new javax.swing.JTextField();
        EmailLabel1 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SignUp_Button = new javax.swing.JButton();
        Name_Filed = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        EmailLabel2 = new javax.swing.JLabel();
        EmailLabel3 = new javax.swing.JLabel();
        loginToggle = new javax.swing.JButton();
        dobChooser = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lEndDateChooser = new datechooser.beans.DateChooserCombo();
        LicenseNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SCN_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(738, 425));
        setMinimumSize(new java.awt.Dimension(738, 425));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\rental.png")); // NOI18N

        TitleLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("C-Rents");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel)
                    .addComponent(Image))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleLabel)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        EmailLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Name");

        Phone_Field.setBackground(new java.awt.Color(255, 255, 255));
        Phone_Field.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Phone_Field.setForeground(new java.awt.Color(0, 0, 0));

        EmailLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel1.setText("Password");

        Password_Field.setBackground(new java.awt.Color(255, 255, 255));
        Password_Field.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Password_Field.setForeground(new java.awt.Color(0, 0, 0));
        Password_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_FieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SignUp");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Already Have an Account ? ");

        SignUp_Button.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SignUp_Button.setText("SignUp");
        SignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ButtonActionPerformed(evt);
            }
        });

        Name_Filed.setBackground(new java.awt.Color(255, 255, 255));
        Name_Filed.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Name_Filed.setForeground(new java.awt.Color(0, 0, 0));
        Name_Filed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_FiledActionPerformed(evt);
            }
        });

        Email_Field.setBackground(new java.awt.Color(255, 255, 255));
        Email_Field.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Email_Field.setForeground(new java.awt.Color(0, 0, 0));

        EmailLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailLabel2.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel2.setText("E-Mail");

        EmailLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailLabel3.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel3.setText("Phone");

        loginToggle.setBackground(new java.awt.Color(153, 153, 153));
        loginToggle.setText("LogIn Here");
        loginToggle.setBorder(null);
        loginToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginToggleActionPerformed(evt);
            }
        });

        dobChooser.setCalendarBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOB");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("License Number ");

        LicenseNumber.setBackground(new java.awt.Color(255, 255, 255));
        LicenseNumber.setForeground(new java.awt.Color(0, 0, 0));
        LicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseNumberActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expire Date");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Social Security Number");

        SCN_Field.setBackground(new java.awt.Color(255, 255, 255));
        SCN_Field.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Phone_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(Name_Filed)
                                .addComponent(EmailLabel)
                                .addComponent(EmailLabel3))
                            .addComponent(jLabel6)
                            .addComponent(SCN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(LicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailLabel1))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(dobChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addComponent(SignUp_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(loginToggle)))
                .addGap(29, 94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailLabel2)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Name_Filed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dobChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SCN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel1)
                    .addComponent(EmailLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Phone_Field)
                    .addComponent(Password_Field))
                .addGap(60, 60, 60)
                .addComponent(SignUp_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginToggle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Password_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_FieldActionPerformed

    }//GEN-LAST:event_Password_FieldActionPerformed

    private void SignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ButtonActionPerformed
        boolean status;
        String scn = SCN_Field.getText();
        String Name = Name_Filed.getText();
        String Email = Email_Field.getText();
        String Phone = Phone_Field.getText();
        String PassWord = Password_Field.getText();
        String licenseNumber = LicenseNumber.getText();
        String dob = dobChooser.getText();
        java.util.Date dobUtil = new java.util.Date(dob);
        String licEDate = lEndDateChooser.getText();
        java.util.Date licEDateUtil = new java.util.Date(licEDate);
        java.util.Date nowDate = new java.util.Date();
        
        if (Name == null || Name.length() == 0) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            status = checkEmailFormat(Email);
            if (status) {
                if (scn.length() == 10) {
                    
                    if (licenseNumber.length() == 10) {
                        
                        if (checkPhoneFormat(Phone)) {
                            
                            if (PassWord.length() > 6) {
                                
                                int age = nowDate.getYear() - dobUtil.getYear();
                                if (age >= 21) {
                                    
                                    if (licEDateUtil.after(nowDate)) {
                                        
                                        Customer customer = new Customer(scn, licenseNumber, dobUtil, licEDateUtil, Name, Email, PassWord, Phone);
                                        if (!db.checkExists(customer)) {
                                            db.addUser(customer);
                                            new CustomerHomePage(customer, con, db).setVisible(true);
                                            this.setVisible(false);
                                        } else {
                                            JOptionPane.showMessageDialog(this, "SCN/Email/Phone already used", "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                        
                                    } else { // INVALID LICENSE NUMBER DATE
                                        JOptionPane.showMessageDialog(this, "You must have a valid driver's license", "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                    
                                } else { // AKBR W T3AL.
                                    JOptionPane.showMessageDialog(this, "You have to be 21 in order to register", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                                
                            } else {// INVALID PASSWORD
                                JOptionPane.showMessageDialog(this, "Password too short", "Error", JOptionPane.ERROR_MESSAGE);
                                
                            }
                            
                        } else {// INVALID PHONE NUMBER
                            JOptionPane.showMessageDialog(this, "Invalid Phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                            
                        }
                        
                    } else { // INVALID LICENSE NUMBER
                        JOptionPane.showMessageDialog(this, "Invalid License Number", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                } else { // INVALID SOCIAL SECURITY NUMBER
                    JOptionPane.showMessageDialog(this, "Invalid SCN", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            } else { // INVALID E-MAIL FORMAT
                JOptionPane.showMessageDialog(this, "Invalid E-Mail Format", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

//        status = checkEmailFormat(Email);
//        if (status) {
//            status = checkPhoneFormat(Phone);
//            if (status) {
//                if (PassWord.length() >= 6) {
//                    try {
//                        status = Register(id, Name, Email, Phone, PassWord);
//                        if (status) {
//                            // GO TO HOME PAGE ...
//                            new HomePage((int) id, con).setVisible(true);
//                            System.out.println("SIGN UP DONE.");
//                        } else {
//                            // POP UP ERROR.
//                            System.out.println("ERROR SIGNING UP...");
//                            JOptionPane.showMessageDialog(this, "Email/Phone Already Exists", "Error", JOptionPane.ERROR_MESSAGE);
//                        }
//                    } catch (SQLException e) {
//                        System.err.println("SQL EXCEPTION...");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Password must be greater than 6 characters", "Error", JOptionPane.ERROR_MESSAGE);
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Invalid Phone Format", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            // POP UP E-MAIL...
//            JOptionPane.showMessageDialog(this, "Invalid E-Mail Format", "Error", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_SignUp_ButtonActionPerformed

    private void loginToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginToggleActionPerformed
        
        this.setVisible(false);
        new UserPage(con, db).setVisible(true);
        

    }//GEN-LAST:event_loginToggleActionPerformed

    private void Name_FiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_FiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_FiledActionPerformed

    private void LicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseNumberActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JLabel EmailLabel2;
    private javax.swing.JLabel EmailLabel3;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Image;
    private javax.swing.JTextField LicenseNumber;
    private javax.swing.JTextField Name_Filed;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JTextField Phone_Field;
    private javax.swing.JTextField SCN_Field;
    private javax.swing.JButton SignUp_Button;
    private javax.swing.JLabel TitleLabel;
    private datechooser.beans.DateChooserCombo dobChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private datechooser.beans.DateChooserCombo lEndDateChooser;
    private javax.swing.JButton loginToggle;
    // End of variables declaration//GEN-END:variables

    private boolean checkEmailFormat(String Email) {
        String regex = "^(.+)@(.+)$";
        
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(Email);
        
        return matcher.matches();
        
    }
    
    private boolean checkPhoneFormat(String Phone) {
        if (Phone.length() != 10) {
            return false;
        } else {
            try {
                int i = Integer.parseInt(Phone);
            } catch (NumberFormatException e) {
                return false;
            }
        }
        
        return true;
    }
    
    public boolean Register(long id, String name, String Email, String Phone, String Password) throws SQLException {
        String q = "insert into users values (? , ? , ? , ?,?)";
        PreparedStatement pstat = con.prepareStatement(q, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        pstat.setInt(1, (int) id);
        pstat.setString(2, name);
        pstat.setString(3, Email);
        pstat.setString(4, Password);
        pstat.setString(5, Phone);
        
        if (!checkExists(Email, Phone)) {
            pstat.execute();
            return true;
        }
        
        return false;
    }
    
    private boolean checkExists(String Email, String Phone) throws SQLException {
        String q = "select * from users where email = ? OR phone = ?";
        PreparedStatement pstat = con.prepareStatement(q, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        
        pstat.setString(1, Email);
        pstat.setString(2, Phone);
        ResultSet rs = pstat.executeQuery();
        rs.beforeFirst();
        if (rs.next()) {
            return true;
        }
        
        return false;
    }
    
}
