/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rent_system;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class editAccountPanel extends javax.swing.JPanel {

    Connection con;
    DB db;
    Customer customer;

    public editAccountPanel(Connection con, DB db, Customer customer) {

        initComponents();
        this.con = con;
        this.db = db;
        this.customer = customer;
        CustomerName.setText(customer.getName());

        //  CustomerName.sett
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChangeComcoBox = new javax.swing.JComboBox<>();
        CustomerName = new javax.swing.JLabel();
        TextFieldChange = new javax.swing.JLabel();
        UpdateTextField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name :  ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("What would you like to change ? ");

        ChangeComcoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "Phone", "Password", " " }));
        ChangeComcoBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChangeComcoBoxItemStateChanged(evt);
            }
        });
        ChangeComcoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeComcoBoxActionPerformed(evt);
            }
        });

        CustomerName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CustomerName.setForeground(new java.awt.Color(0, 0, 0));
        CustomerName.setText("Name");

        TextFieldChange.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldChange.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldChange.setText("New Value :");

        UpdateButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustomerName)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TextFieldChange)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(ChangeComcoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ChangeComcoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CustomerName))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldChange)
                    .addComponent(UpdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(UpdateButton)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed

        String UpdateBox = ChangeComcoBox.getItemAt(ChangeComcoBox.getSelectedIndex()).toString();
        String NewFiled = UpdateTextField.getText();

        UpdateCus(UpdateBox, NewFiled);
        
        if (db.updateUser(customer,UpdateBox)){
            JOptionPane.showMessageDialog(this, customer.getName() +" has been updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(this, customer.getName() +" has not been updated", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ChangeComcoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeComcoBoxActionPerformed
        // String NewFiled = UpdateTextField.getText();
    }//GEN-LAST:event_ChangeComcoBoxActionPerformed

    private void ChangeComcoBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChangeComcoBoxItemStateChanged
      // String NewFiled = UpdateTextField.getText();
    }//GEN-LAST:event_ChangeComcoBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChangeComcoBox;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JLabel TextFieldChange;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UpdateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public void UpdateCus(String Field, String NewField) {


        if (Field.equalsIgnoreCase("Email")) {
            customer.setEmail(NewField);
        } else if (Field.equalsIgnoreCase("Phone")) {
            customer.setPhone(NewField);
        } else {
            customer.setPassword(NewField);
        }
       


    }

}
